#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
创建Maya兼容的FBX文件
使用官方FBX SDK生成与参考文件相同版本的FBX文件
"""

import fbx
import FbxCommon
import os
import sys
import json

def create_maya_compatible_fbx(joints_data=None, output_file="maya_compatible_skeleton.fbx"):
    """创建Maya兼容的FBX文件"""
    print("🚀 创建Maya兼容的FBX文件...")
    
    # 创建FBX管理器
    manager = fbx.FbxManager.Create()
    if not manager:
        print("❌ 无法创建FBX管理器")
        return False
    
    # 创建IO设置 - 设置为FBX 2020版本（7700）
    ios = fbx.FbxIOSettings.Create(manager, fbx.IOSROOT)
    manager.SetIOSettings(ios)
    
    # 设置导出格式为FBX 2020
    ios.SetBoolProp(fbx.EXP_FBX_MATERIAL, True)
    ios.SetBoolProp(fbx.EXP_FBX_TEXTURE, True)
    ios.SetBoolProp(fbx.EXP_FBX_EMBEDDED, False)
    ios.SetBoolProp(fbx.EXP_FBX_SHAPE, True)
    ios.SetBoolProp(fbx.EXP_FBX_GOBO, True)
    ios.SetBoolProp(fbx.EXP_FBX_ANIMATION, True)
    ios.SetBoolProp(fbx.EXP_FBX_GLOBAL_SETTINGS, True)
    
    # 创建场景
    scene = fbx.FbxScene.Create(manager, "SkeletonScene")
    if not scene:
        print("❌ 无法创建FBX场景")
        manager.Destroy()
        return False
    
    # 设置场景信息
    scene_info = scene.GetSceneInfo()
    if scene_info:
        scene_info.mTitle = "Human Skeleton"
        scene_info.mSubject = "Generated by Python FBX SDK"
        scene_info.mAuthor = "FBX Generator"
        scene_info.mRevision = "1.0"
        scene_info.mKeywords = "skeleton, human, animation"
        scene_info.mComment = "Maya compatible skeleton file"
    
    print("✅ FBX管理器和场景创建成功")
    
    # 创建骨骼层次结构
    root_node = scene.GetRootNode()
    
    if joints_data:
        joints = create_skeleton_from_data(scene, root_node, joints_data)
    else:
        joints = create_default_skeleton(scene, root_node)
    
    # 设置全局设置
    global_settings = scene.GetGlobalSettings()
    global_settings.SetSystemUnit(fbx.FbxSystemUnit.cm)  # 使用厘米单位
    global_settings.SetOriginalUpAxis(fbx.FbxAxisSystem.MayaYUp)  # Maya Y轴向上
    global_settings.SetTimeMode(fbx.FbxTime.eFrames30)  # 30fps
    
    # 保存文件
    success = save_fbx_file_v7700(manager, scene, output_file)
    
    # 清理资源
    manager.Destroy()
    
    if success:
        print(f"🎉 Maya兼容FBX文件创建成功: {output_file}")
        # 检查文件大小
        if os.path.exists(output_file):
            file_size = os.path.getsize(output_file)
            print(f"📊 文件大小: {file_size:,} 字节")
        return True
    else:
        print("❌ FBX文件创建失败")
        return False

def create_default_skeleton(scene, root_node):
    """创建默认的人体骨骼结构"""
    print("🦴 创建默认人体骨骼结构...")
    
    joints = {}
    
    # 定义完整的人体骨骼层次结构（基于COCO格式）
    joint_hierarchy = {
        # 主干
        'Hips': {'parent': None, 'position': (0, 100, 0)},
        'Spine': {'parent': 'Hips', 'position': (0, 110, 0)},
        'Spine1': {'parent': 'Spine', 'position': (0, 125, 0)},
        'Spine2': {'parent': 'Spine1', 'position': (0, 140, 0)},
        'Neck': {'parent': 'Spine2', 'position': (0, 155, 0)},
        'Head': {'parent': 'Neck', 'position': (0, 170, 0)},
        
        # 左臂
        'LeftShoulder': {'parent': 'Spine2', 'position': (-5, 150, 0)},
        'LeftArm': {'parent': 'LeftShoulder', 'position': (-20, 150, 0)},
        'LeftForeArm': {'parent': 'LeftArm', 'position': (-45, 150, 0)},
        'LeftHand': {'parent': 'LeftForeArm', 'position': (-70, 150, 0)},
        
        # 右臂
        'RightShoulder': {'parent': 'Spine2', 'position': (5, 150, 0)},
        'RightArm': {'parent': 'RightShoulder', 'position': (20, 150, 0)},
        'RightForeArm': {'parent': 'RightArm', 'position': (45, 150, 0)},
        'RightHand': {'parent': 'RightForeArm', 'position': (70, 150, 0)},
        
        # 左腿
        'LeftUpLeg': {'parent': 'Hips', 'position': (-10, 100, 0)},
        'LeftLeg': {'parent': 'LeftUpLeg', 'position': (-10, 60, 0)},
        'LeftFoot': {'parent': 'LeftLeg', 'position': (-10, 10, 0)},
        'LeftToeBase': {'parent': 'LeftFoot', 'position': (-10, 0, 15)},
        
        # 右腿
        'RightUpLeg': {'parent': 'Hips', 'position': (10, 100, 0)},
        'RightLeg': {'parent': 'RightUpLeg', 'position': (10, 60, 0)},
        'RightFoot': {'parent': 'RightLeg', 'position': (10, 10, 0)},
        'RightToeBase': {'parent': 'RightFoot', 'position': (10, 0, 15)}
    }
    
    return create_joints_from_hierarchy(scene, root_node, joint_hierarchy)

def create_skeleton_from_data(scene, root_node, joints_data):
    """从关节数据创建骨骼"""
    print("🦴 从数据创建骨骼结构...")
    
    # 这里可以根据实际的关节数据格式进行解析
    # 暂时使用默认结构
    return create_default_skeleton(scene, root_node)

def create_joints_from_hierarchy(scene, root_node, joint_hierarchy):
    """从层次结构创建关节"""
    joints = {}
    
    # 按依赖顺序创建关节
    created_joints = set()
    
    def create_joint_recursive(joint_name):
        if joint_name in created_joints:
            return joints[joint_name]
        
        joint_info = joint_hierarchy[joint_name]
        
        # 创建骨骼属性
        skeleton_attr = fbx.FbxSkeleton.Create(scene, f"{joint_name}_Skeleton")
        
        if joint_info['parent'] is None:
            # 根骨骼
            skeleton_attr.SetSkeletonType(fbx.FbxSkeleton.eRoot)
            skeleton_attr.Size.Set(1.0)
        else:
            # 肢体骨骼
            skeleton_attr.SetSkeletonType(fbx.FbxSkeleton.eLimbNode)
            skeleton_attr.Size.Set(1.0)
        
        # 创建节点
        joint_node = fbx.FbxNode.Create(scene, joint_name)
        joint_node.SetNodeAttribute(skeleton_attr)
        
        # 设置变换
        pos = joint_info['position']
        joint_node.LclTranslation.Set(fbx.FbxDouble3(pos[0], pos[1], pos[2]))
        joint_node.LclRotation.Set(fbx.FbxDouble3(0, 0, 0))
        joint_node.LclScaling.Set(fbx.FbxDouble3(1, 1, 1))
        
        # 设置节点属性
        joint_node.SetShadingMode(fbx.FbxNode.eWireFrame)
        joint_node.SetVisibility(True)
        
        joints[joint_name] = joint_node
        created_joints.add(joint_name)
        
        # 建立父子关系
        if joint_info['parent'] is None:
            root_node.AddChild(joint_node)
        else:
            parent_joint = create_joint_recursive(joint_info['parent'])
            parent_joint.AddChild(joint_node)
        
        print(f"  ✅ 创建关节: {joint_name}")
        return joint_node
    
    # 创建所有关节
    for joint_name in joint_hierarchy.keys():
        create_joint_recursive(joint_name)
    
    print(f"🎯 骨骼结构创建完成，共 {len(joints)} 个关节")
    return joints

def save_fbx_file_v7700(manager, scene, filename):
    """保存为FBX 2020版本（7700）"""
    print(f"💾 保存FBX文件: {filename}")
    
    # 创建导出器
    exporter = fbx.FbxExporter.Create(manager, "")
    
    # 设置导出格式为二进制FBX 2020
    format_index = -1
    format_count = manager.GetIOPluginRegistry().GetWriterFormatCount()
    
    for i in range(format_count):
        format_desc = manager.GetIOPluginRegistry().GetWriterFormatDescription(i)
        if "FBX binary" in format_desc and "2020" in format_desc:
            format_index = i
            break
    
    if format_index == -1:
        # 如果找不到2020格式，使用默认的二进制格式
        for i in range(format_count):
            format_desc = manager.GetIOPluginRegistry().GetWriterFormatDescription(i)
            if "FBX binary" in format_desc:
                format_index = i
                break
    
    # 初始化导出器
    if not exporter.Initialize(filename, format_index, manager.GetIOSettings()):
        print(f"❌ 无法初始化导出器: {exporter.GetStatus().GetErrorString()}")
        exporter.Destroy()
        return False
    
    # 设置导出选项
    ios = manager.GetIOSettings()
    ios.SetBoolProp(fbx.EXP_FBX_MATERIAL, True)
    ios.SetBoolProp(fbx.EXP_FBX_TEXTURE, True)
    ios.SetBoolProp(fbx.EXP_FBX_EMBEDDED, False)
    ios.SetBoolProp(fbx.EXP_FBX_SHAPE, True)
    ios.SetBoolProp(fbx.EXP_FBX_GOBO, True)
    ios.SetBoolProp(fbx.EXP_FBX_ANIMATION, True)
    ios.SetBoolProp(fbx.EXP_FBX_GLOBAL_SETTINGS, True)
    
    # 导出场景
    result = exporter.Export(scene)
    
    # 清理导出器
    exporter.Destroy()
    
    if result:
        print("✅ FBX文件保存成功")
        return True
    else:
        print("❌ FBX文件保存失败")
        return False

def load_joints_from_existing_fbx(fbx_file):
    """从现有FBX文件加载关节数据"""
    try:
        with open(fbx_file, 'rb') as f:
            # 这里可以解析现有的FBX文件获取关节信息
            # 暂时返回None使用默认结构
            pass
    except:
        pass
    return None

def main():
    """主函数"""
    print("🧪 Maya兼容FBX生成器")
    print("=" * 50)
    
    try:
        # 尝试从用户的FBX文件加载关节数据
        user_fbx = "e:\\image_3d\\text2dance\\output\\sample_video\\fbx_output\\person_0001_skeleton.fbx"
        joints_data = load_joints_from_existing_fbx(user_fbx)
        
        # 创建Maya兼容的FBX文件
        output_file = "maya_compatible_skeleton_v7700.fbx"
        success = create_maya_compatible_fbx(joints_data, output_file)
        
        if success:
            print("\n🎉 创建完成！")
            print("\n📋 Maya导入测试步骤:")
            print("1. 打开Maya 2020或更高版本")
            print(f"2. File -> Import -> 选择 {output_file}")
            print("3. 检查Outliner中的骨骼层次结构")
            print("4. 与参考文件 jingang_13_c+_004.fbx 进行对比")
            
            print("\n💡 关键改进:")
            print("- 使用FBX 2020版本（7700）格式")
            print("- 标准的Maya骨骼命名规范")
            print("- 正确的骨骼类型设置")
            print("- Maya兼容的坐标系统")
            print("- 完整的场景信息设置")
        else:
            print("❌ 创建失败")
            return 1
            
    except Exception as e:
        print(f"❌ 程序执行出错: {e}")
        import traceback
        traceback.print_exc()
        return 1
    
    return 0

if __name__ == "__main__":
    sys.exit(main())